"""Ticker -> sector mapping for the Dhaka Stock Exchange.

Why this is a static file rather than a scrape: DSE's industry pages
(companylistbyindustry.php, ltp_industry.php) render their tables in JavaScript,
so a server-side fetch returns only the full-market price strip that appears on
every page. Scraping them yields every company under whichever sector loaded
last, which is worse than useless — it silently corrupts sector analysis.

Sector names match DSE's own 22 official industries so they join cleanly against
the sectoral median P/E table.

Maintenance: new listings appear a few times a year. If a ticker you care about
shows as "Unclassified" in the brief, add it here. The pattern rules below catch
most cases automatically.
"""

from __future__ import annotations

import re

# DSE's official industry names
BANK = "Bank"
CEMENT = "Cement"
CERAMIC = "Ceramics Sector"
ENGINEERING = "Engineering"
FININST = "Financial Institutions"
FOOD = "Food & Allied"
FUEL = "Fuel & Power"
INSURANCE = "Insurance"
IT = "IT Sector"
JUTE = "Jute"
MISC = "Miscellaneous"
MUTUAL = "Mutual Funds"
PAPER = "Paper & Printing"
PHARMA = "Pharmaceuticals & Chemicals"
SERVICES = "Services & Real Estate"
TANNERY = "Tannery Industries"
TELECOM = "Telecommunication"
TEXTILE = "Textile"
TRAVEL = "Travel & Leisure"
BOND = "Corporate Bond"
GSEC = "G-SEC (T.Bond)"

EXPLICIT: dict[str, str] = {}


def _add(sector: str, codes: str) -> None:
    for c in codes.split():
        EXPLICIT[c.upper()] = sector


_add(TELECOM, "GP ROBI BSCCL")

_add(BANK, """
    ABBANK ALARABANK BANKASIA BRACBANK CITYBANK DHAKABANK DUTCHBANGL EBL
    EXIMBANK FIRSTSBANK GLOBALBANK ICBIBANK IFIC ISLAMIBANK JAMUNABANK MERCANBANK
    MIDLANDBNK MTB NBL NCCBANK NRBBANK NRBCBANK ONEBANKPLC PREMIERBAN PRIMEBANK
    PUBALIBANK RUPALIBANK SBACBANK SHAHJABANK SIBL SOUTHEASTB STANDBANKL
    TRUSTBANK UCB UNIONBANK UTTARABANK CITYGENINS BENGALWTL
""")

_add(FININST, """
    BDFINANCE BIFC DBH FAREASTFIN FASFIN GSPFINANCE IDLC ILFSL IPDC ISLAMICFIN
    LANKABAFIN MIDASFIN NHFIL PHOENIXFIN PLFSL PREMIERLEA PRIMEFIN UNITEDFIN
    UTTARAFIN ICB BAYLEASING CVOPRL
""")

_add(PHARMA, """
    ACI ACIFORMULA ACMELAB ACMEPL ACTIVEFINE ADVENT AFCAGRO AMBEEPHA BXPHARMA
    BEACONPHAR CENTRALPHL GLAXOSMITH IBNSINA INDOBANGL JMISMDL KOHINOOR LIBRAINFU
    ORIONINFU ORIONPHARM PHARMAID RENATA SALVOCHEM SILCOPHL SILVAPHL SQURPHARMA
    TECHNODRUG WATACHEM NAVANAPHAR ACMEPL
""")

_add(FUEL, """
    BARKAPOWER BARAKAPOWER CVO DESCO DOREENPWR EASTRNLUB GBBPOWER INTRACO
    JAMUNAOIL KHULNAPOWER LINDEBD MJLBD MEGHNAPET MPETROLEUM PADMAOIL POWERGRID
    SHAHJIBAZAR SUMITPOWER TITASGAS UNITEDPOWR ENERGYPAC ACFL
""")

_add(ENGINEERING, """
    AFTABAUTO ANWARGALV APOLOISPAT ATLASBANG AZIZPIPES BBS BBSCABLES BDAUTOCA
    BDLAMPS BDTHAI BENGALWTL BSRMLTD BSRMSTEEL COPPERTECH DESHBANDHU DOMINAGE
    ECABLES GPHISPAT IFADAUTOS KAY&QUE MONNOAGML NAVANACNG NPOLYMER NTLTUBES
    OIMEX QUASEMIND RANFOUNDRY RENWICKJA RSRMSTEEL RUNNERAUTO SINGERBD SSSTEEL
    WALTONHIL WMSHIPYARD YPL NAHEEACP
""")

_add(CEMENT, "ARAMITCEM CONFIDCEM HEIDELBCEM LHBL MICEMENT PREMIERCEM MEGHNACEM")

_add(FOOD, """
    AMANFEED AMCL(PRAN) APEXFOODS BATBC BDTHAIFOOD BEACHHATCH EMERALDOIL FINEFOODS
    FUWANGFOOD GEMINISEA GHAIL GOLDENSON MARICO MEGHNAMILK NTC OLYMPIC RAHIMAFOOD
    RDFOOD SHYAMPSUG UNILEVERCL ZEALBANGLA BANGAS LOVELLO
""")

_add(TEXTILE, """
    AL-HAJTEX ALLTEX ANLIMAYARN APEXSPINN ARGONDENIM CNATEX DACCADYE DELTASPINN
    DESCO2 DSHGARME DULAMIACOT ENVOYTEX ESQUIRENIT ETL EVINCE FAMILYTEX FARBAGRO
    FEKDIL GENNEXT HAMI HFL HRTEX HWAWELLTEX KATTALITEX KDSALTD MAKSONSPIN
    MALEKSPIN MATINSPINN METROSPIN MHSML MITHUNKNIT MLDYEING MOZAFFAR NEWLINE
    NURANI PARAMOUNT PRIMETEX PTL QUEENSOUTH REGENTTEX RINGSHINE RNSPIN SAFKOSPINN
    SAIHAMCOT SAIHAMTEX SAMATALETH SHASHADNIM SHEPHERD SIMTEX SONARGAON SQUARETEXT
    STYLECRAFT TALLUSPIN TAMIJTEX TOSRIFA TUNGHAI VFSTDL ZAHINTEX ZAHEENSPIN
    BEXIMCO
""")

_add(INSURANCE, """
    AGRANINS ASIAINS ASIAPACINS BGIC BNICL CENTRALINS CITYGENINS CONTININS
    CRYSTALINS DESHGENINS DHAKAINS EASTERNINS EASTLAND FEDERALINS GLOBALINS
    GREENDELT ISLAMIINS JANATAINS KARNAPHULI MEGHNAINS MERCINS NITOLINS NORTHRNINS
    PARAMOUNTI PEOPLESINS PHENIXINS PIONEERINS PRAGATIINS PRAGATILIF PRIMEINSUR
    PRIMELIFE PROGRESLIF PROVATIINS PURABIGEN RELIANCE1 REPUBLIC RUPALIINS
    RUPALILIFE SANDHANINS SONALIANSH SONARBAINS STANDARINS TAKAFULINS TRUSTINS
    UNIONINS UNITEDINS SICL SBLIC
""")

_add(IT, "AAMRANET AAMRATECH ADNTEL AGNISYSL BDCOM DAFODILCOM EGEN GENEXIL INTECH ITC ISNLTD")

_add(CERAMIC, "FUWANGCER MONNOCERA RAKCERAMIC SHURWID STANCERAM")

_add(TANNERY, "APEXFOOT APEXTANRY BATASHOE FORTUNE LEGACYFOOT SAMATALETH")

_add(PAPER, "BASHUNDHARA HAKKANIPUL KHULNAPRIN PAPERPROC SONALIPAPR MONNOFABR")

_add(JUTE, "JUTESPINN NORTHERN SONALIAASH")

_add(SERVICES, "BDSERVICE EASTERNHOU SAPORTL SUMITSPORT UNIQUEHRL PENINSULA")

_add(TRAVEL, "BEACHHATCH SEAPEARL UNITEDAIR THELDBL")

_add(MISC, """
    ARAMIT BERGERPBL BEXIMCO2 GQBALLPEN INDEXAGRO KDSALTD MIRACLEIND NFML
    SINOBANGLA SAVAREFR SIPLC USMANIAGL WONDERLAND ACMEPL ADVENT2 SILCOPHL2
    KHANBROTHR
""")

_add(CEMENT, "CROWNCEMNT")
_add(BANK, "GIB")
_add(FUEL, "EPGL KPCL BDWELDING2 UPGDCL")
_add(ENGINEERING, "BDWELDING NAHEEACP")
_add(INSURANCE, "CLICL EIL DGIC ICICL SBLIC NLI")
_add(PHARMA, "GHCL")
_add(PAPER, "BPML BPPL")
_add(SERVICES, "BSC BSCPLC EHL JHRML DSSL")
_add(TRAVEL, "BESTHLDNG")
_add(MISC, "KEYACOSMET AIL AOL EIL2 IBP")
_add(MUTUAL, "CAPITECGBF FBFIF GRAMEENS2 ICB3RDNRB ICBAGRANI1 ICBAMCL2ND ICBSONALI1")

# Pattern rules for anything not listed above. Order matters — first match wins.
PATTERNS: list[tuple[str, str]] = [
    (r"(1STMF|MF$|MUTUAL|\dMF|MF\d|BALANCE|GBF$|^ICB.*\d|UNITFUND)", MUTUAL),
    (r"(TBOND|TB\d|BGTB)", GSEC),
    (r"(BOND|PBOND|SUKUK|DEBEN)", BOND),
    (r"(INS$|INSUR|GENINS|LIFE|LIF$)", INSURANCE),
    (r"BANK", BANK),
    (r"(FIN$|FINANCE|LEAS|CREDIT)", FININST),
    (r"(PHARMA|PHAR|DRUG|LAB$|CHEM|MEDIC)", PHARMA),
    (r"(POWER|PWR|ENERGY|OIL$|GAS|FUEL|PETRO|SOLAR)", FUEL),
    (r"(TEX|SPIN|YARN|DYE|COT|KNIT|DENIM|FABR|GARME)", TEXTILE),
    (r"(CEM$|CEMENT)", CEMENT),
    (r"(FOOD|FEED|AGRO|MILK|SUGAR|BEVER)", FOOD),
    (r"(CERAM|TILES)", CERAMIC),
    (r"(STEEL|ISPAT|CABLE|AUTO|ENGIN|SHIPYARD|PIPE)", ENGINEERING),
    (r"(TECH|SOFT|SYS|NET$|COM$|DIGITAL)", IT),
    (r"(HOTEL|RESORT|AIR$|TOUR|HRL)", TRAVEL),
    (r"(PAPER|PRINT)", PAPER),
    (r"(JUTE)", JUTE),
]

_COMPILED = [(re.compile(p), s) for p, s in PATTERNS]


def sector_for(code: str) -> str:
    """Best-effort sector for a DSE trading code."""
    code = (code or "").upper().strip()
    if not code:
        return "Unclassified"
    if code in EXPLICIT:
        return EXPLICIT[code]
    for rx, sector in _COMPILED:
        if rx.search(code):
            return sector
    return "Unclassified"


def build_map(codes) -> dict[str, str]:
    return {c: sector_for(c) for c in codes}


def coverage(codes) -> dict:
    mapped = [c for c in codes if sector_for(c) != "Unclassified"]
    return {
        "total": len(codes),
        "classified": len(mapped),
        "pct": round(len(mapped) / len(codes) * 100, 1) if codes else 0.0,
        "unclassified": sorted(c for c in codes if sector_for(c) == "Unclassified"),
    }
